---
title: "Effect of Pre-Meeting Small Talk on Perceived Social Cohesion"
author: "Amaddio, Patrick, Schimmler, Feng"
date: "2023-06-04"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: united
    highlight: tango
    code_folding: hide
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# load user level data
library(readr)
data <- read_delim("data_project_982541_2023_06_29.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

# add treatment variable
data$exp_condition[data$rnd_pg_6658842 == 6658840] <- 0
data$exp_condition[data$rnd_pg_6658842 == 6658841] <- 1

colnames(data)[which(names(data) == "v_1")] <- "data_policy"
colnames(data)[which(names(data) == "v_12")] <- "c_1"
colnames(data)[which(names(data) == "v_13")] <- "c_2"
colnames(data)[which(names(data) == "v_14")] <- "c_3"
colnames(data)[which(names(data) == "v_15")] <- "c_4"
colnames(data)[which(names(data) == "v_16")] <- "c_5"
colnames(data)[which(names(data) == "v_17")] <- "c_6"
colnames(data)[which(names(data) == "v_9")] <- "manip_ch"
colnames(data)[which(names(data) == "v_20")] <- "gender"
colnames(data)[which(names(data) == "v_10")] <- "age"
colnames(data)[which(names(data) == "v_11")] <- "exp"
# keep only variables of interest
data <- data[c("c_1", "c_2", "c_3", "c_4", "c_5", "c_6", "manip_ch", "gender", "age", "exp", "exp_condition")]
data$cohesion_mean <- rowMeans(
    cbind(
      data$c_1,
      data$c_2,
      data$c_3,
      data$c_4,
      data$c_5,
      data$c_6),
    na.rm = TRUE
  )

# - v_1: Datenschutz
# - p_0001: external VP

### outcome: (group) cohesion

# v_12: Ich habe das Gefühl, dass ich zu diesem Team dazu gehöre.
# v_13: Ich bin froh, Teil dieses Teams zu sein.
# v_14: Ich sehe mich als Teil dieses Teams.
# v_15: Dieses Team ist eines der Besten überhaupt.
# v_16: Ich habe das Gefühl, dass ich ein Mitglied dieses Teams bin.
# v_17: Ich bin damit zufrieden, ein Teil dieses Teams zu sein.

# scale
# - 1	Starke Ablehnung
# - 2	 
# - 3	 
# - 4	Neutral
# - 5	 
# - 6	 
# - 7	Starke Zustimmung

# mainpulation check:

# v_9: Ich denke, dass die Agenda es ermöglicht, dass sich die Kollegen und Kolleginnen besser kennenlernen können.

### demographic variables:

# v_20: Ich identifiziere mich als...

# - 1	Männlich
# - 2	Weiblich
# - 3	Divers
# - 4	Keine Angabe
# - 5	Eigene Angabe

# v_21: Gechlecht, eigene Angabe

# v_10: Wie alt sind Sie?

# v_11: Haben Sie Erfahrung mit videobasierten Online-Meetings?

# - 1	Ja
# - 2	Nein
```


# Variables

```{r, include=TRUE}
str(data)
```

# Descriptive Statistics

Global Descriptive statistics whithout group mean.

```{r, include=TRUE}
library(psych)
psych::describe(data)
```

Means depending on the treatment (group: 1) vs control (group: 0)

```{r, include=TRUE}
psych::describeBy(data, data$exp_condition)
```

# Analysis of a variance

## Without Control Variables

```{r, include=TRUE}
one.way <- aov(exp_condition ~ cohesion_mean, data = data)
summary(one.way)
```

So far the F(1,158) = 8.92, p = .003 is significant.

## With Age and Gender Controlled

```{r, include=TRUE}
one.way <- aov(exp_condition ~ cohesion_mean + age + gender, data = data)
summary(one.way)
```

Neither gender nor age has a significant impact on team cohesion.

So far the F(1,156) = 8.84, p = .003 is significant.